from __future__ import annotations

import re
from dataclasses import dataclass

from .deploy_parser import DeployDocument, parse_deploy
from .models import FieldChange


@dataclass(frozen=True)
class PatchResult:
    document: DeployDocument
    changes: tuple[FieldChange, ...]
    warnings: tuple[str, ...]


def _format_like(original: str, value: int | float | str) -> str:
    if original.startswith(('"', "'")):
        return f"{original[0]}{value}{original[0]}"
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _patch_field(text: str, document: DeployDocument, command: str, parameter: str, value: object) -> str:
    occurrence = document.command(command)
    pattern = re.compile(
        rf"(?P<prefix>\b{re.escape(parameter)}\s*=\s*)(?P<value>\"(?:[^\"\\]|\\.)*\"|'(?:[^'\\]|\\.)*'|[^,;\s]+)",
        re.IGNORECASE,
    )
    block = text[occurrence.start : occurrence.end]
    match = pattern.search(block)
    if not match:
        raise KeyError(f"{command}.{parameter} not present; refusing to invent it")
    replacement = match.group("prefix") + _format_like(match.group("value"), value)  # type: ignore[arg-type]
    patched_block = block[: match.start()] + replacement + block[match.end() :]
    return text[: occurrence.start] + patched_block + text[occurrence.end :]


def patch_timing(
    document: DeployDocument,
    *,
    echo_interval_seconds: int,
    echo_duration_seconds: int,
    current_enabled: bool,
    current_interval_seconds: int,
    current_duration_seconds: int,
) -> PatchResult:
    if echo_interval_seconds <= 0 or echo_duration_seconds <= 0:
        raise ValueError("echo interval and duration must be positive")
    if echo_duration_seconds > echo_interval_seconds:
        raise ValueError("echo duration must not exceed interval")
    if current_duration_seconds > current_interval_seconds:
        raise ValueError("current duration must not exceed interval")
    sample_count = echo_duration_seconds * 4
    if sample_count != int(sample_count):
        raise ValueError("echo duration must produce an integer sample count at 4 Hz")
    requested: list[tuple[str, str, object]] = [
        ("SETPLAN", "MIBURST", echo_interval_seconds),
        ("SETBURST", "SR", 4),
        ("SETBURST", "NS", int(sample_count)),
        ("SETPLAN", "AVG", 1 if current_enabled else 0),
    ]
    if current_enabled:
        requested.extend(
            [
                ("SETPLAN", "MIAVG", current_interval_seconds),
                ("SETAVG", "AI", current_duration_seconds),
            ]
        )
    changes = tuple(
        FieldChange(command, parameter, document.get(command, parameter), value, document.get(command, parameter) != value)
        for command, parameter, value in requested
    )
    text = document.text
    current_doc = document
    for change in changes:
        if change.changed:
            text = _patch_field(text, current_doc, change.command, change.parameter, change.requested)
            current_doc = parse_deploy(text)
    warnings = [
        "Metadata generated by Signature Deployment was preserved and may now be stale.",
        "Optimized phase calculated but not written to Nortek timing field because phase-offset command semantics have not been verified.",
    ]
    if current_enabled and document.get("SETAVG", "AI") != current_duration_seconds:
        warnings.append(
            "REQUIRES_INSTRUMENT_LIMIT_VALIDATION: SETAVG.AI changed; preserve NPING and validate with GETAVGLIM / SAVE / GETERROR / READCFG."
        )
    return PatchResult(current_doc, changes, tuple(warnings))
